# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'NativeNestingRN' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '4.0.1'

	config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'NativeNestingRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NativeNestingRNUITests' do
    # Pods for testing
  end

  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end

end
